/**:
  graph_manager:
    ros__parameters:
      invariants:
        points:
          "0" : 
            sigma : 0.1
            epsilon : 0.6
            mindist : 0
        points&normal :
          "0" :
            sigp : 0.5
            epsp : 0.5
            sign : 0.10
            epsn : 0.35
          "1":
            sigp : 0.5
            epsp : 0.5
            sign : 0.10
            epsn : 0.35
      thresholds : 
        local_intralevel : 0.7
        local_interlevel : 0.7
        global : 0.8
      dbscan : 
        eps : 0.01
        min_samples : 1
      levels : 
        name : 
        - "Finite Room"
        - "Plane"
        datatype : 
          floor : "points"
          Finite Room : "points"
          Plane : "points&normal"
        clipper_invariants : 
          floor : 0
          Finite Room : 0
          Plane: 0
